FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5173

# Default command, can be overridden by docker-compose
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
